export const ingredients = {
  "meat": [
    "Chicken",
    "Beef",
    "Pork",
    "Lamb",
    "Ground Meat",
    "Bacon",
    "Sausages",
    "Ground Turkey",
    "Duck",
    "Turkey",
    "Salmon",
    "Shrimp",
    "Tuna",
    "Crab",
    "Lobster",
    "Squid",
    "Venison",
    "Veal",
    "Ham",
    "Goat"
  ],
  "vegetables": [
    "Tomatoes",
    "Spinach",
    "Broccoli",
    "Bell Peppers",
    "Carrots",
    "Onions",
    "Cauliflower",
    "Zucchini",
    "Eggplant",
    "Kale",
    "Potatoes",
    "Cabbage",
    "Mushrooms",
    "Cucumbers",
    "Asparagus",
    "Celery",
    "Green Beans",
    "Lettuce",
    "Radishes",
    "Pumpkin"
  ],
  "fruits": [
    "Apples",
    "Bananas",
    "Strawberries",
    "Oranges",
    "Grapes",
    "Mangoes",
    "Pineapples",
    "Blueberries",
    "Watermelon",
    "Avocados",
    "Peaches",
    "Pears",
    "Raspberries",
    "Kiwi",
    "Blackberries",
    "Lemons",
    "Cherries",
    "Cantaloupe",
    "Apricots",
    "Coconut"
  ],
  "spices": [
    "Basil",
    "Oregano",
    "Thyme",
    "Cinnamon",
    "Cumin",
    "Paprika",
    "Turmeric",
    "Garlic Powder",
    "Ginger",
    "Chili Powder",
    "Coriander",
    "Nutmeg",
    "Rosemary",
    "Cardamom",
    "Cloves",
    "Allspice",
    "Bay Leaves",
    "Mustard Seeds",
    "Fenugreek",
    "Saffron"
  ],
  "grains": [
    "Brown Rice",
    "Quinoa",
    "Oats",
    "Whole Wheat Flour",
    "Barley",
    "Buckwheat",
    "Couscous",
    "Millet",
    "Farro",
    "Cornmeal",
    "White Rice",
    "Bulgur",
    "Rye",
    "Semolina",
    "Amaranth",
    "Spelt",
    "Wheat Bran",
    "Sorghum",
    "Triticale",
    "Wild Rice"
  ]
}

